# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LiquidityConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("trade_type", models.CharField(choices=[("BUY", "Achat"), ("SELL", "Vente")], max_length=4)),
                ("min_amount", models.DecimalField(decimal_places=8, default=0, help_text="Quantité minimale (en USDT)", max_digits=20)),
                ("max_amount", models.DecimalField(blank=True, decimal_places=8, help_text="Quantité maximale (en USDT), vide = pas de limite", max_digits=20, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Config liquidité", "verbose_name_plural": "Configs liquidité"},
        ),
        migrations.CreateModel(
            name="PlatformConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Plateforme P2P", "verbose_name_plural": "Plateformes P2P"},
        ),
        migrations.CreateModel(
            name="RateAdjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope", models.CharField(choices=[("global", "Global"), ("currency", "Par devise"), ("country", "Par pays (XOF)"), ("trade_type", "Par type (achat/vente)")], default="global", max_length=20)),
                ("currency", models.CharField(blank=True, help_text="Ex: XOF, GHS, XAF", max_length=10)),
                ("country", models.CharField(blank=True, help_text="Ex: Bénin, Sénégal (pour XOF)", max_length=50)),
                ("trade_type", models.CharField(blank=True, choices=[("BUY", "Achat"), ("SELL", "Vente")], max_length=4)),
                ("mode", models.CharField(choices=[("percent", "Pourcentage (%)"), ("fixed", "Montant fixe")], max_length=10)),
                ("value", models.DecimalField(decimal_places=8, help_text="Pourcentage (ex: 2.5) ou montant fixe", max_digits=20)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Ajustement de taux", "verbose_name_plural": "Ajustements de taux"},
        ),
        migrations.AddConstraint(
            model_name="liquidityconfig",
            constraint=models.UniqueConstraint(fields=("trade_type",), name="core_liquidityconfig_trade_type_unique"),
        ),
    ]
