# Generated by Django 5.2.11 on 2026-02-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiat', models.CharField(max_length=10)),
                ('trade_type', models.CharField(max_length=4)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('platform', models.CharField(max_length=30)),
                ('rank', models.PositiveSmallIntegerField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meilleur taux',
                'verbose_name_plural': 'Meilleurs taux',
                'ordering': ['fiat', 'trade_type', 'country', 'platform', 'rank'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='liquidityconfig',
            name='core_liquidityconfig_trade_type_unique',
        ),
        migrations.AlterUniqueTogether(
            name='liquidityconfig',
            unique_together={('trade_type',)},
        ),
        migrations.AlterUniqueTogether(
            name='bestrate',
            unique_together={('fiat', 'trade_type', 'country', 'platform', 'rank')},
        ),
    ]
