# Generated by Django 5.2.11 on 2026-02-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_best_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestrate',
            options={'ordering': ['fiat', 'trade_type', 'country', 'platform', 'rate'], 'verbose_name': 'Meilleur taux', 'verbose_name_plural': 'Meilleurs taux'},
        ),
        migrations.AlterUniqueTogether(
            name='bestrate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bestrate',
            name='rank',
        ),
    ]
