# Generated by Django 5.2.11 on 2026-02-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_bestrate_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestRatesRefreshConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_minutes', models.PositiveSmallIntegerField(choices=[(1, '1 min'), (5, '5 min'), (10, '10 min'), (15, '15 min'), (30, '30 min')], default=5, help_text='Fréquence de rafraîchissement (cron doit appeler la commande toutes les 1 min).')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Désactiver pour arrêter le refresh automatique.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Config refresh best rates',
                'verbose_name_plural': 'Config refresh best rates',
            },
        ),
    ]
