# Generated by Django 5.2.11 on 2026-02-07 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_best_rates_refresh_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='monthly_quota',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre max d'appels par mois (vide = illimité).", null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(blank=True, help_text="Laisser vide pour générer à l'enregistrement.", max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(help_text='Usage ou identifiant client', max_length=100),
        ),
        migrations.CreateModel(
            name='APIKeyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='core.apikey')),
            ],
            options={
                'verbose_name': 'Usage API (mois)',
                'verbose_name_plural': 'Usages API (mois)',
                'ordering': ['api_key', '-period'],
                'unique_together': {('api_key', 'period')},
            },
        ),
    ]
