# Generated by Django 5.2.11 on 2026-02-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_apikey_usage_and_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_call', models.DecimalField(decimal_places=6, default=0, help_text='Prix facturé par appel API (ex: 0.001 pour 0,001 €/appel).', max_digits=12)),
                ('currency', models.CharField(default='EUR', help_text='Devise (ex: EUR, USD, XOF).', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Config facturation',
                'verbose_name_plural': 'Config facturation',
            },
        ),
        migrations.AddField(
            model_name='apikey',
            name='billing_exempt',
            field=models.BooleanField(default=False, help_text='Si coché, cette clé est exemptée de facturation (montant = 0).'),
        ),
    ]
