# Generated by Django 5.2.11 on 2026-02-09 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_billing_config_and_exempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code ISO (ex. XOF, GHS, USD)', max_length=10, unique=True)),
                ('name', models.CharField(blank=True, help_text='Nom affiché (ex. Franc CFA BCEAO)', max_length=100)),
                ('active', models.BooleanField(default=True, help_text='Désactiver pour exclure du refresh des taux')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage (plus petit = en premier)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'Devises',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code ISO pays (ex. BJ, SN, CI)', max_length=10)),
                ('name', models.CharField(help_text='Nom du pays', max_length=100)),
                ('active', models.BooleanField(default=True, help_text='Désactiver pour exclure du refresh')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(help_text='Devise à laquelle ce pays est rattaché', on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='core.currency')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['currency', 'order', 'code'],
                'unique_together': {('currency', 'code')},
            },
        ),
    ]
