# Generated by hand for RateAdjustment simplification

from django.db import migrations, models


def build_target_from_legacy(apps, schema_editor):
    RateAdjustment = apps.get_model("core", "RateAdjustment")
    for r in RateAdjustment.objects.all():
        if r.scope == "global" and not r.currency:
            r.target = "global"
        else:
            base = r.currency or "global"
            parts = [base]
            if r.country:
                parts.append(r.country)
            if r.trade_type:
                parts.append(r.trade_type)
            r.target = ":".join(parts)
        r.save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_seed_west_africa_currencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="rateadjustment",
            name="target",
            field=models.CharField(
                default="global",
                help_text="global | XOF | XOF:BJ | XOF:SELL | XOF:BJ:SELL",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(build_target_from_legacy, noop_reverse),
        migrations.RemoveField(model_name="rateadjustment", name="scope"),
        migrations.RemoveField(model_name="rateadjustment", name="currency"),
        migrations.RemoveField(model_name="rateadjustment", name="country"),
        migrations.RemoveField(model_name="rateadjustment", name="trade_type"),
    ]
