# Generated by hand

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_simplify_rate_adjustment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossRateAdjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "target",
                    models.CharField(
                        default="cross",
                        help_text="cross | cross:SOURCE | cross:SOURCE:CIBLE (ex. cross:XOF:GHS)",
                        max_length=50,
                    ),
                ),
                ("mode", models.CharField(choices=[("percent", "Pourcentage (%)"), ("fixed", "Montant fixe")], max_length=10)),
                (
                    "value_buy",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        help_text="% ou montant fixe sur le leg BUY. Positif = majoration, négatif = minoration.",
                        max_digits=20,
                    ),
                ),
                (
                    "value_sell",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        help_text="% ou montant fixe sur le leg SELL. Positif = majoration, négatif = minoration.",
                        max_digits=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ajustement taux croisé",
                "verbose_name_plural": "Ajustements taux croisé",
            },
        ),
    ]
