# Generated by hand - snapshot offres brutes (source de vérité)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_cross_rate_adjustment"),
    ]

    operations = [
        migrations.CreateModel(
            name="OffersSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("platform", models.CharField(max_length=30)),
                ("fiat", models.CharField(max_length=10)),
                ("trade_type", models.CharField(max_length=4)),
                ("country", models.CharField(blank=True, default="", max_length=10)),
                ("data", models.JSONField(default=list, help_text="Liste d'offres brutes (price, min_fiat, max_fiat, advertiser, etc.)")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Snapshot offres",
                "verbose_name_plural": "Snapshots offres",
                "ordering": ["platform", "fiat", "trade_type", "country"],
                "unique_together": {("platform", "fiat", "trade_type", "country")},
            },
        ),
    ]
