# Generated by hand - option inclusion pour liquidité

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_offers_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquidityconfig",
            name="require_inclusion",
            field=models.BooleanField(
                default=False,
                help_text="Si coché : garder seulement les offres dont [min_fiat, max_fiat] est inclus dans [min, max]. Sinon : chevauchement suffit.",
            ),
        ),
    ]
