# Generated by hand - filtre liquidité en fiat ou USDT

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_liquidity_require_inclusion"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquidityconfig",
            name="amount_in_fiat",
            field=models.BooleanField(
                default=True,
                help_text="Si coché : min/max config et plage offre en fiat (min_fiat, max_fiat). Sinon : en USDT (min_usdt, max_usdt).",
            ),
        ),
    ]
