# Generated by Django 5.2.11 on 2026-02-14 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_liquidity_amount_in_fiat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidityconfig',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Montant fiat maximum, vide = pas de limite', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='liquidityconfig',
            name='min_amount',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Montant fiat minimum (ex. FCFA)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='liquidityconfig',
            name='require_inclusion',
            field=models.BooleanField(default=False, help_text='Si coché : garder seulement les offres dont la plage est incluse dans [min, max]. Sinon : chevauchement suffit.'),
        ),
        migrations.AlterField(
            model_name='rateadjustment',
            name='target',
            field=models.CharField(default='SELL', help_text='Offres: SELL | BUY | XOF:SELL | XOF:BUY | XOF:BJ:SELL…', max_length=50),
        ),
        migrations.AlterField(
            model_name='rateadjustment',
            name='value',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.CreateModel(
            name='AdvertiserUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Id annonceur (reference retournée dans les offres)', max_length=64)),
                ('fiat', models.CharField(blank=True, help_text='Devise (ex. XOF)', max_length=10)),
                ('trade_type', models.CharField(blank=True, help_text='BUY ou SELL', max_length=4)),
                ('amount', models.DecimalField(blank=True, decimal_places=8, help_text='Montant de la transaction (optionnel)', max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_usages', to='core.apikey')),
            ],
            options={
                'verbose_name': 'Usage annonceur (déclaration client)',
                'verbose_name_plural': 'Usages annonceur (déclarations clients)',
                'ordering': ['-created_at'],
            },
        ),
    ]
