# Generated by hand

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_advertiser_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="rateadjustment",
            name="minorer",
            field=models.BooleanField(
                default=False,
                help_text="Si coché : minorer (réduire le prix). Sinon : majorer (augmenter le prix).",
            ),
        ),
        migrations.AddField(
            model_name="crossrateadjustment",
            name="minorer_buy",
            field=models.BooleanField(
                default=False,
                help_text="Si coché : minorer le leg BUY (réduire). Sinon : majorer.",
            ),
        ),
        migrations.AddField(
            model_name="crossrateadjustment",
            name="minorer_sell",
            field=models.BooleanField(
                default=False,
                help_text="Si coché : minorer le leg SELL (réduire). Sinon : majorer.",
            ),
        ),
    ]
