# Generated by Django 5.0 - rates n'a pas de modèles pour l'instant
from django.db import migrations


class Migration(migrations.Migration):

    initial = True
    dependencies = []
    operations = []
