# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RateHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_currency", models.CharField(max_length=10)),
                ("target_currency", models.CharField(max_length=10)),
                ("rate", models.DecimalField(decimal_places=8, max_digits=20)),
                ("trade_type", models.CharField(max_length=4)),
                ("platform", models.CharField(max_length=30)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "Historique taux", "verbose_name_plural": "Historiques taux", "ordering": ["-created_at"]},
        ),
    ]
